on:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo1
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "rogoyal-keyVault"
        secrets: 'testSecret'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: myGetSecretAction
