#on: [push]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo1
    - uses: actions/checkout@master
    - uses: azure/login@releases/azcloud-v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_CHINA }}
        environment: 'AzureChinaCloud' 
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "azchinacloudkv"
        secrets: 'testsecret1,testsecret2'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: myGetSecretAction
